#!/usr/bin/env python3
"""Génère CSV, SQL, JSON et catalogue Markdown pour ref_media."""

from __future__ import annotations

import csv
import json
from pathlib import Path

COLUMNS = [
    "id_media",
    "code",
    "nom",
    "pays_code",
    "pays_nom",
    "langue",
    "type_media",
    "support",
    "periodicite",
    "thematique",
    "couverture",
    "groupe_media",
    "ville",
    "url",
    "priorite_rp",
    "actif",
    "notes",
    "source_liste",
]

# source_liste:
#   EXEMPLE = lignes France servant de modèle de colonnes
#   CIBLE   = pays demandés (BE, CH, PT, ES)

ROWS: list[dict[str, object]] = [
    # --- France : exemple de structure (ref_media existant) ---
    ("MED-FR-001", "LEMONDE", "Le Monde", "FR", "France", "fr",
     "Presse quotidienne", "Print+Digital", "Quotidien", "Généraliste",
     "Nationale", "Groupe Le Monde", "Paris", "https://www.lemonde.fr", 1, True,
     "Quotidien de référence. Titre d'exemple pour caler les colonnes.", "EXEMPLE"),
    ("MED-FR-002", "LEFIGARO", "Le Figaro", "FR", "France", "fr",
     "Presse quotidienne", "Print+Digital", "Quotidien", "Généraliste",
     "Nationale", "Groupe Figaro", "Paris", "https://www.lefigaro.fr", 1, True,
     "Quotidien national conservateur.", "EXEMPLE"),
    ("MED-FR-003", "LESECHOS", "Les Echos", "FR", "France", "fr",
     "Presse quotidienne", "Print+Digital", "Quotidien", "Économie",
     "Nationale", "Groupe Les Echos / LVMH", "Paris", "https://www.lesechos.fr", 1, True,
     "Quotidien économique de référence.", "EXEMPLE"),
    ("MED-FR-004", "AFP", "Agence France-Presse", "FR", "France", "fr",
     "Agence de presse", "Agence", "Continu", "Généraliste",
     "Internationale", "AFP", "Paris", "https://www.afp.com", 1, True,
     "Agence nationale / internationale.", "EXEMPLE"),
    ("MED-FR-005", "FRANCEINTER", "France Inter", "FR", "France", "fr",
     "Radio", "Audiovisuel", "Continu", "Généraliste",
     "Nationale", "Radio France", "Paris", "https://www.radiofrance.fr/franceinter", 1, True,
     "Radio généraliste de service public.", "EXEMPLE"),
    ("MED-FR-006", "TF1", "TF1", "FR", "France", "fr",
     "Télévision", "Audiovisuel", "Continu", "Généraliste",
     "Nationale", "Groupe TF1", "Boulogne-Billancourt", "https://www.tf1.fr", 1, True,
     "Première chaîne privée.", "EXEMPLE"),
    ("MED-FR-007", "FRANCE2", "France 2", "FR", "France", "fr",
     "Télévision", "Audiovisuel", "Continu", "Généraliste",
     "Nationale", "France Télévisions", "Paris", "https://www.france.tv/france-2", 1, True,
     "Chaîne généraliste de service public.", "EXEMPLE"),
    ("MED-FR-008", "BFMTV", "BFMTV", "FR", "France", "fr",
     "Télévision", "Audiovisuel", "Continu", "Généraliste",
     "Nationale", "Altice Media", "Paris", "https://www.bfmtv.com", 1, True,
     "Chaîne d'information en continu.", "EXEMPLE"),
    ("MED-FR-009", "MEDIAPART", "Mediapart", "FR", "France", "fr",
     "Web natif", "Digital", "Continu", "Généraliste",
     "Nationale", "Société éditrice de Mediapart", "Paris", "https://www.mediapart.fr", 2, True,
     "Pure player d'enquête.", "EXEMPLE"),
    ("MED-FR-010", "LEXPRESS", "L'Express", "FR", "France", "fr",
     "Presse magazine", "Print+Digital", "Hebdomadaire", "Généraliste",
     "Nationale", "Groupe L'Express", "Paris", "https://www.lexpress.fr", 2, True,
     "News magazine national.", "EXEMPLE"),
    # --- Belgique ---
    ("MED-BE-001", "LESOIR", "Le Soir", "BE", "Belgique", "fr",
     "Presse quotidienne", "Print+Digital", "Quotidien", "Généraliste",
     "Nationale", "Groupe Rossel", "Bruxelles", "https://www.lesoir.be", 1, True,
     "Quotidien francophone de référence.", "CIBLE"),
    ("MED-BE-002", "LALIBRE", "La Libre Belgique", "BE", "Belgique", "fr",
     "Presse quotidienne", "Print+Digital", "Quotidien", "Généraliste",
     "Nationale", "IPM Group", "Bruxelles", "https://www.lalibre.be", 1, True,
     "Quotidien francophone, ligne plutôt centre-droit.", "CIBLE"),
    ("MED-BE-003", "LADH", "La DH / La Dernière Heure", "BE", "Belgique", "fr",
     "Presse quotidienne", "Print+Digital", "Quotidien", "Généraliste",
     "Nationale", "IPM Group", "Bruxelles", "https://www.dhnet.be", 2, True,
     "Quotidien populaire francophone, fort sur le sport.", "CIBLE"),
    ("MED-BE-004", "LAVENIR", "L'Avenir", "BE", "Belgique", "fr",
     "Presse quotidienne", "Print+Digital", "Quotidien", "Régional",
     "Régionale", "IPM Group", "Namur", "https://www.lavenir.net", 2, True,
     "PQR wallonne (éditions provinciales).", "CIBLE"),
    ("MED-BE-005", "SUDINFO", "Sudinfo", "BE", "Belgique", "fr",
     "Presse quotidienne", "Print+Digital", "Quotidien", "Régional",
     "Régionale", "Groupe Rossel", "Liège", "https://www.sudinfo.be",
     2, True, "Porte les titres Sud Presse (La Meuse, La Nouvelle Gazette, etc.).", "CIBLE"),
    ("MED-BE-006", "HLN", "Het Laatste Nieuws", "BE", "Belgique", "nl",
     "Presse quotidienne", "Print+Digital", "Quotidien", "Généraliste",
     "Nationale", "DPG Media", "Anvers", "https://www.hln.be", 1, True,
     "Premier quotidien néerlandophone en audience.", "CIBLE"),
    ("MED-BE-007", "NIEUWSBLAD", "Het Nieuwsblad", "BE", "Belgique", "nl",
     "Presse quotidienne", "Print+Digital", "Quotidien", "Généraliste",
     "Nationale", "Mediahuis", "Anvers", "https://www.nieuwsblad.be", 1, True,
     "Quotidien populaire flamand.", "CIBLE"),
    ("MED-BE-008", "STANDAARD", "De Standaard", "BE", "Belgique", "nl",
     "Presse quotidienne", "Print+Digital", "Quotidien", "Généraliste",
     "Nationale", "Mediahuis", "Bruxelles", "https://www.standaard.be", 1, True,
     "Quotidien flamand de référence.", "CIBLE"),
    ("MED-BE-009", "DEMORGEN", "De Morgen", "BE", "Belgique", "nl",
     "Presse quotidienne", "Print+Digital", "Quotidien", "Généraliste",
     "Nationale", "DPG Media", "Bruxelles", "https://www.demorgen.be", 1, True,
     "Quotidien flamand, ligne progressiste.", "CIBLE"),
    ("MED-BE-010", "GVA", "Gazet van Antwerpen", "BE", "Belgique", "nl",
     "Presse quotidienne", "Print+Digital", "Quotidien", "Régional",
     "Régionale", "Mediahuis", "Anvers", "https://www.gva.be", 2, True,
     "PQR anversoise.", "CIBLE"),
    ("MED-BE-011", "HBVL", "Het Belang van Limburg", "BE", "Belgique", "nl",
     "Presse quotidienne", "Print+Digital", "Quotidien", "Régional",
     "Régionale", "Mediahuis", "Hasselt", "https://www.hbvl.be", 2, True,
     "PQR limbourgeoise.", "CIBLE"),
    ("MED-BE-012", "LECHO", "L'Echo", "BE", "Belgique", "fr",
     "Presse quotidienne", "Print+Digital", "Quotidien", "Économie",
     "Nationale", "Mediafin (Rossel / Roularta)", "Bruxelles", "https://www.lecho.be",
     1, True, "Quotidien économique francophone.", "CIBLE"),
    ("MED-BE-013", "DETIJD", "De Tijd", "BE", "Belgique", "nl",
     "Presse quotidienne", "Print+Digital", "Quotidien", "Économie",
     "Nationale", "Mediafin (Rossel / Roularta)", "Bruxelles", "https://www.tijd.be",
     1, True, "Quotidien économique flamand, pendant de L'Echo.", "CIBLE"),
    ("MED-BE-014", "LEVIF", "Le Vif", "BE", "Belgique", "fr",
     "Presse magazine", "Print+Digital", "Hebdomadaire", "Généraliste",
     "Nationale", "Roularta Media Group", "Bruxelles", "https://www.levif.be",
     2, True, "News magazine francophone.", "CIBLE"),
    ("MED-BE-015", "KNACK", "Knack", "BE", "Belgique", "nl",
     "Presse magazine", "Print+Digital", "Hebdomadaire", "Généraliste",
     "Nationale", "Roularta Media Group", "Bruxelles", "https://www.knack.be",
     2, True, "News magazine flamand.", "CIBLE"),
    ("MED-BE-016", "TRENDS", "Trends / Trends-Tendances", "BE", "Belgique", "nl",
     "Presse magazine", "Print+Digital", "Hebdomadaire", "Économie",
     "Nationale", "Roularta Media Group", "Bruxelles", "https://www.trends.be",
     2, True, "Magazine économique ; édition FR : Tendances.", "CIBLE"),
    ("MED-BE-017", "RTBF", "RTBF / La Une", "BE", "Belgique", "fr",
     "Télévision", "Audiovisuel", "Continu", "Généraliste",
     "Nationale", "RTBF", "Bruxelles", "https://www.rtbf.be", 1, True,
     "Service public francophone (La Une, Tipik, La Trois, Auvio).", "CIBLE"),
    ("MED-BE-018", "RTLTVI", "RTL-TVI", "BE", "Belgique", "fr",
     "Télévision", "Audiovisuel", "Continu", "Généraliste",
     "Nationale", "RTL Belgium", "Bruxelles", "https://www.rtl.be", 1, True,
     "Première chaîne privée francophone.", "CIBLE"),
    ("MED-BE-019", "LN24", "LN24", "BE", "Belgique", "fr",
     "Télévision", "Audiovisuel", "Continu", "Généraliste",
     "Nationale", "IPM Group", "Bruxelles", "https://www.ln24.be", 2, True,
     "Chaîne d'information en continu francophone.", "CIBLE"),
    ("MED-BE-020", "VRTNWS", "VRT NWS", "BE", "Belgique", "nl",
     "Télévision", "Audiovisuel", "Continu", "Généraliste",
     "Nationale", "VRT", "Bruxelles", "https://www.vrt.be/vrtnws", 1, True,
     "Information du service public flamand (Eén, Canvas, VRT NWS).", "CIBLE"),
    ("MED-BE-021", "VTM", "VTM", "BE", "Belgique", "nl",
     "Télévision", "Audiovisuel", "Continu", "Généraliste",
     "Nationale", "DPG Media", "Vilvoorde", "https://www.vtm.be", 1, True,
     "Première chaîne privée flamande.", "CIBLE"),
    ("MED-BE-022", "LAPREMIERE", "La Première", "BE", "Belgique", "fr",
     "Radio", "Audiovisuel", "Continu", "Généraliste",
     "Nationale", "RTBF", "Bruxelles", "https://www.rtbf.be/lapremiere", 2, True,
     "Radio généraliste de service public francophone.", "CIBLE"),
    ("MED-BE-023", "BELRTL", "Bel RTL", "BE", "Belgique", "fr",
     "Radio", "Audiovisuel", "Continu", "Généraliste",
     "Nationale", "RTL Belgium", "Bruxelles", "https://www.belrtl.be", 2, True,
     "Radio généraliste privée francophone.", "CIBLE"),
    ("MED-BE-024", "RADIOCONTACT", "Radio Contact", "BE", "Belgique", "fr",
     "Radio", "Audiovisuel", "Continu", "Généraliste",
     "Nationale", "RTL Belgium", "Bruxelles", "https://www.radiocontact.be", 3, True,
     "Radio musicale ; utile pour visibilité grand public.", "CIBLE"),
    ("MED-BE-025", "RADIO1", "Radio 1", "BE", "Belgique", "nl",
     "Radio", "Audiovisuel", "Continu", "Généraliste",
     "Nationale", "VRT", "Bruxelles", "https://www.radio1.be", 2, True,
     "Radio généraliste de service public flamand.", "CIBLE"),
    ("MED-BE-026", "QMUSIC", "Qmusic", "BE", "Belgique", "nl",
     "Radio", "Audiovisuel", "Continu", "Généraliste",
     "Nationale", "DPG Media", "Vilvoorde", "https://qmusic.be", 3, True,
     "Radio musicale flamande à forte audience.", "CIBLE"),
    ("MED-BE-027", "BELGA", "Belga", "BE", "Belgique", "fr",
     "Agence de presse", "Agence", "Continu", "Généraliste",
     "Nationale", "Belga News Agency", "Bruxelles", "https://www.belga.be", 1, True,
     "Agence nationale (FR/NL, sélection EN). Fil d'entrée prioritaire des CP.", "CIBLE"),
    ("MED-BE-028", "BRUZZ", "BRUZZ", "BE", "Belgique", "nl",
     "Web natif", "Digital", "Continu", "Régional",
     "Régionale", "Vlaams-Brusselse Media", "Bruxelles", "https://www.bruzz.be",
     2, True, "Média bruxellois (NL, contenus aussi en FR/EN).", "CIBLE"),
    ("MED-BE-029", "GRENZECHO", "GrenzEcho", "BE", "Belgique", "de",
     "Presse quotidienne", "Print+Digital", "Quotidien", "Régional",
     "Régionale", "Grenz-Echo / Groupe Rossel", "Eupen", "https://www.grenzecho.net",
     3, True, "Quotidien de la Communauté germanophone.", "CIBLE"),
    ("MED-BE-030", "7SUR7", "7sur7", "BE", "Belgique", "fr",
     "Web natif", "Digital", "Continu", "Généraliste",
     "Nationale", "DPG Media", "Anvers", "https://www.7sur7.be", 2, True,
     "Pure player francophone du groupe HLN.", "CIBLE"),
    ("MED-BE-031", "METROBE", "Metro Belgique", "BE", "Belgique", "fr",
     "Presse quotidienne", "Print+Digital", "Quotidien", "Généraliste",
     "Nationale", "Groupe Rossel", "Bruxelles", "https://www.metrotime.be",
     3, True, "Gratuit bilingue (FR/NL) de transport.", "CIBLE"),
    ("MED-BE-032", "APACHE", "Apache", "BE", "Belgique", "nl",
     "Web natif", "Digital", "Continu", "Généraliste",
     "Nationale", "Apache", "Anvers", "https://www.apache.be", 3, True,
     "Pure player d'enquête flamand.", "CIBLE"),
    # --- Suisse ---
    ("MED-CH-001", "NZZ", "Neue Zürcher Zeitung", "CH", "Suisse", "de",
     "Presse quotidienne", "Print+Digital", "Quotidien", "Généraliste",
     "Nationale", "NZZ Mediengruppe", "Zurich", "https://www.nzz.ch", 1, True,
     "Quotidien alémanique de référence (politique, international, éco).", "CIBLE"),
    ("MED-CH-002", "TAGI", "Tages-Anzeiger", "CH", "Suisse", "de",
     "Presse quotidienne", "Print+Digital", "Quotidien", "Généraliste",
     "Nationale", "TX Group", "Zurich", "https://www.tagesanzeiger.ch", 1, True,
     "Quotidien zurichois à portée nationale.", "CIBLE"),
    ("MED-CH-003", "BLICK", "Blick", "CH", "Suisse", "de",
     "Presse quotidienne", "Print+Digital", "Quotidien", "Généraliste",
     "Nationale", "Ringier", "Zurich", "https://www.blick.ch", 1, True,
     "Quotidien populaire ; très fort digital / vidéo.", "CIBLE"),
    ("MED-CH-004", "20MINDE", "20 Minuten", "CH", "Suisse", "de",
     "Presse quotidienne", "Print+Digital", "Quotidien", "Généraliste",
     "Nationale", "TX Group", "Zurich", "https://www.20min.ch", 1, True,
     "Gratuit pendulaire, plus forte portée alémanique.", "CIBLE"),
    ("MED-CH-005", "DERBUND", "Der Bund", "CH", "Suisse", "de",
     "Presse quotidienne", "Print+Digital", "Quotidien", "Régional",
     "Régionale", "TX Group", "Berne", "https://www.derbund.ch", 2, True,
     "Quotidien bernois. Figure sur la liste COPA des médias principaux.", "CIBLE"),
    ("MED-CH-006", "BAZ", "Basler Zeitung", "CH", "Suisse", "de",
     "Presse quotidienne", "Print+Digital", "Quotidien", "Régional",
     "Régionale", "TX Group", "Bâle", "https://www.bazonline.ch", 2, True,
     "Quotidien bâlois.", "CIBLE"),
    ("MED-CH-007", "LETEMPS", "Le Temps", "CH", "Suisse", "fr",
     "Presse quotidienne", "Print+Digital", "Quotidien", "Généraliste",
     "Nationale", "Fondation Aventinus", "Genève", "https://www.letemps.ch", 1, True,
     "Quotidien romand de référence. Liste COPA.", "CIBLE"),
    ("MED-CH-008", "24HEURES", "24 heures", "CH", "Suisse", "fr",
     "Presse quotidienne", "Print+Digital", "Quotidien", "Régional",
     "Régionale", "TX Group", "Lausanne", "https://www.24heures.ch", 1, True,
     "Quotidien vaudois de référence.", "CIBLE"),
    ("MED-CH-009", "TDG", "Tribune de Genève", "CH", "Suisse", "fr",
     "Presse quotidienne", "Print+Digital", "Quotidien", "Régional",
     "Régionale", "TX Group", "Genève", "https://www.tdg.ch", 1, True,
     "Quotidien genevois.", "CIBLE"),
    ("MED-CH-010", "20MINFR", "20 minutes", "CH", "Suisse", "fr",
     "Presse quotidienne", "Print+Digital", "Quotidien", "Généraliste",
     "Nationale", "TX Group", "Lausanne", "https://www.20min.ch/fr", 1, True,
     "Gratuit pendulaire romand.", "CIBLE"),
    ("MED-CH-011", "LEMATIN", "Le Matin / lematin.ch", "CH", "Suisse", "fr",
     "Web natif", "Digital", "Continu", "Généraliste",
     "Nationale", "TX Group", "Lausanne", "https://www.lematin.ch", 2, True,
     "Marque populaire romande ; print quotidien arrêté, digital + Le Matin Dimanche.", "CIBLE"),
    ("MED-CH-012", "LALIBERTECH", "La Liberté", "CH", "Suisse", "fr",
     "Presse quotidienne", "Print+Digital", "Quotidien", "Régional",
     "Régionale", "Groupe Saint-Paul", "Fribourg", "https://www.laliberte.ch", 2, True,
     "Quotidien fribourgeois.", "CIBLE"),
    ("MED-CH-013", "CDT", "Corriere del Ticino", "CH", "Suisse", "it",
     "Presse quotidienne", "Print+Digital", "Quotidien", "Généraliste",
     "Régionale", "Fondazione Corriere del Ticino", "Muzzano", "https://www.cdt.ch",
     1, True, "Quotidien tessinois de référence. Liste COPA.", "CIBLE"),
    ("MED-CH-014", "HANDELSZEITUNG", "Handelszeitung", "CH", "Suisse", "de",
     "Presse magazine", "Print+Digital", "Hebdomadaire", "Économie",
     "Nationale", "Ringier", "Zurich", "https://www.handelszeitung.ch", 2, True,
     "Hebdomadaire économique alémanique.", "CIBLE"),
    ("MED-CH-015", "BILANZ", "Bilanz", "CH", "Suisse", "de",
     "Presse magazine", "Print+Digital", "Mensuel", "Économie",
     "Nationale", "Ringier", "Zurich", "https://www.bilanz.ch", 2, True,
     "Magazine économique alémanique.", "CIBLE"),
    ("MED-CH-016", "BILAN", "Bilan", "CH", "Suisse", "fr",
     "Presse magazine", "Print+Digital", "Mensuel", "Économie",
     "Nationale", "Ringier", "Lausanne", "https://www.bilan.ch", 2, True,
     "Magazine économique romand.", "CIBLE"),
    ("MED-CH-017", "AGEFI", "L'Agefi", "CH", "Suisse", "fr",
     "Presse quotidienne", "Print+Digital", "Quotidien", "Économie",
     "Nationale", "Agefi SA", "Lausanne", "https://www.agefi.com", 1, True,
     "Quotidien financier romand. Liste COPA.", "CIBLE"),
    ("MED-CH-018", "FUW", "Finanz und Wirtschaft", "CH", "Suisse", "de",
     "Presse quotidienne", "Print+Digital", "Bihebdomadaire", "Économie",
     "Nationale", "NZZ Mediengruppe", "Zurich", "https://www.fuw.ch", 2, True,
     "Titre financier alémanique.", "CIBLE"),
    ("MED-CH-019", "SRF", "SRF", "CH", "Suisse", "de",
     "Télévision", "Audiovisuel", "Continu", "Généraliste",
     "Nationale", "SRG SSR", "Zurich", "https://www.srf.ch", 1, True,
     "Unité alémanique du service public (TV + radio). Liste COPA.", "CIBLE"),
    ("MED-CH-020", "RTS", "RTS", "CH", "Suisse", "fr",
     "Télévision", "Audiovisuel", "Continu", "Généraliste",
     "Nationale", "SRG SSR", "Genève", "https://www.rts.ch", 1, True,
     "Unité romande du service public (TV + radio). Liste COPA.", "CIBLE"),
    ("MED-CH-021", "RSI", "RSI", "CH", "Suisse", "it",
     "Télévision", "Audiovisuel", "Continu", "Généraliste",
     "Régionale", "SRG SSR", "Lugano", "https://www.rsi.ch", 1, True,
     "Unité italophone du service public. Liste COPA.", "CIBLE"),
    ("MED-CH-022", "RTS1ERE", "RTS La 1ère", "CH", "Suisse", "fr",
     "Radio", "Audiovisuel", "Continu", "Généraliste",
     "Nationale", "SRG SSR", "Lausanne", "https://www.rts.ch/audio-podcast/live/la-1ere",
     2, True, "Radio généraliste romande de service public.", "CIBLE"),
    ("MED-CH-023", "SWI", "SWI swissinfo.ch", "CH", "Suisse", "fr",
     "Web natif", "Digital", "Continu", "Généraliste",
     "Internationale", "SRG SSR", "Berne", "https://www.swissinfo.ch", 1, True,
     "Offre internationale de la SSR (plusieurs langues). Liste COPA.", "CIBLE"),
    ("MED-CH-024", "KEYSTONE", "Keystone-ATS", "CH", "Suisse", "fr",
     "Agence de presse", "Agence", "Continu", "Généraliste",
     "Nationale", "Keystone-SDA-ATS", "Berne", "https://www.keystone-sda.ch", 1, True,
     "Agence nationale (DE/FR/IT).", "CIBLE"),
    ("MED-CH-025", "AWP", "AWP Finanznachrichten", "CH", "Suisse", "de",
     "Agence de presse", "Agence", "Continu", "Économie",
     "Nationale", "AWP", "Zurich", "https://www.awp.ch", 1, True,
     "Agence financière. Liste COPA (avec Reuters / Bloomberg).", "CIBLE"),
    ("MED-CH-026", "WATSON", "watson", "CH", "Suisse", "de",
     "Web natif", "Digital", "Continu", "Généraliste",
     "Nationale", "CH Media", "Zurich", "https://www.watson.ch", 2, True,
     "Pure player alémanique à forte audience jeune.", "CIBLE"),
    ("MED-CH-027", "WELTWOCHE", "Die Weltwoche", "CH", "Suisse", "de",
     "Presse magazine", "Print+Digital", "Hebdomadaire", "Généraliste",
     "Nationale", "Weltwoche Verlags AG", "Zurich", "https://www.weltwoche.ch",
     3, True, "Hebdomadaire d'opinion alémanique.", "CIBLE"),
    ("MED-CH-028", "BEOBACHTER", "Beobachter", "CH", "Suisse", "de",
     "Presse magazine", "Print+Digital", "Bimensuel", "Généraliste",
     "Nationale", "Ringier", "Zurich", "https://www.beobachter.ch", 3, True,
     "Magazine conseil / société à large portée.", "CIBLE"),
    ("MED-CH-029", "ILLUSTRE", "L'Illustré", "CH", "Suisse", "fr",
     "Presse magazine", "Print+Digital", "Hebdomadaire", "People",
     "Nationale", "Ringier", "Lausanne", "https://www.illustre.ch", 3, True,
     "Magazine people / société romand.", "CIBLE"),
    ("MED-CH-030", "RTR", "RTR", "CH", "Suisse", "rm",
     "Radio", "Audiovisuel", "Continu", "Généraliste",
     "Régionale", "SRG SSR", "Coire", "https://www.rtr.ch", 3, True,
     "Unité romanche du service public.", "CIBLE"),
    # --- Portugal ---
    ("MED-PT-001", "PUBLICO", "Público", "PT", "Portugal", "pt",
     "Presse quotidienne", "Print+Digital", "Quotidien", "Généraliste",
     "Nationale", "Sonaecom", "Lisbonne", "https://www.publico.pt", 1, True,
     "Quotidien de référence.", "CIBLE"),
    ("MED-PT-002", "EXPRESSO", "Expresso", "PT", "Portugal", "pt",
     "Presse magazine", "Print+Digital", "Hebdomadaire", "Généraliste",
     "Nationale", "Impresa (MFE actionnaire 2026)", "Lisbonne", "https://expresso.pt",
     1, True, "Hebdomadaire le plus lu en diffusion payante.", "CIBLE"),
    ("MED-PT-003", "JN", "Jornal de Notícias", "PT", "Portugal", "pt",
     "Presse quotidienne", "Print+Digital", "Quotidien", "Généraliste",
     "Nationale", "Notícias Ilimitadas", "Porto", "https://www.jn.pt", 1, True,
     "Quotidien de Porto à portée nationale ; forte confiance DNR 2026.", "CIBLE"),
    ("MED-PT-004", "DN", "Diário de Notícias", "PT", "Portugal", "pt",
     "Presse quotidienne", "Print+Digital", "Quotidien", "Généraliste",
     "Nationale", "Global Media Group", "Lisbonne", "https://www.dn.pt", 2, True,
     "Quotidien historique lisboète.", "CIBLE"),
    ("MED-PT-005", "CM", "Correio da Manhã", "PT", "Portugal", "pt",
     "Presse quotidienne", "Print+Digital", "Quotidien", "Généraliste",
     "Nationale", "Medialivre", "Lisbonne", "https://www.cmjornal.pt", 1, True,
     "Quotidien populaire à plus forte diffusion.", "CIBLE"),
    ("MED-PT-006", "OBSERVADOR", "Observador", "PT", "Portugal", "pt",
     "Web natif", "Digital", "Continu", "Généraliste",
     "Nationale", "Observador On Time", "Lisbonne", "https://observador.pt", 1, True,
     "Pure player généraliste + Rádio Observador.", "CIBLE"),
    ("MED-PT-007", "NEGOCIOS", "Jornal de Negócios", "PT", "Portugal", "pt",
     "Presse quotidienne", "Print+Digital", "Quotidien", "Économie",
     "Nationale", "Medialivre", "Lisbonne", "https://www.jornaldenegocios.pt", 1, True,
     "Quotidien économique.", "CIBLE"),
    ("MED-PT-008", "ECO", "ECO", "PT", "Portugal", "pt",
     "Web natif", "Digital", "Continu", "Économie",
     "Nationale", "Swipe News", "Lisbonne", "https://eco.sapo.pt", 1, True,
     "Pure player économique.", "CIBLE"),
    ("MED-PT-009", "VISAO", "Visão", "PT", "Portugal", "pt",
     "Presse magazine", "Print+Digital", "Hebdomadaire", "Généraliste",
     "Nationale", "Trust in News", "Lisbonne", "https://visao.pt", 2, True,
     "News magazine.", "CIBLE"),
    ("MED-PT-010", "SABADO", "Sábado", "PT", "Portugal", "pt",
     "Presse magazine", "Print+Digital", "Hebdomadaire", "Généraliste",
     "Nationale", "Medialivre", "Lisbonne", "https://www.sabado.pt", 2, True,
     "News magazine populaire.", "CIBLE"),
    ("MED-PT-011", "EXAME", "Exame", "PT", "Portugal", "pt",
     "Presse magazine", "Print+Digital", "Mensuel", "Économie",
     "Nationale", "Trust in News", "Lisbonne", "https://visao.pt/exame", 2, True,
     "Magazine économique / entreprises.", "CIBLE"),
    ("MED-PT-012", "RTP1", "RTP1", "PT", "Portugal", "pt",
     "Télévision", "Audiovisuel", "Continu", "Généraliste",
     "Nationale", "RTP", "Lisbonne", "https://www.rtp.pt", 1, True,
     "Chaîne généraliste de service public.", "CIBLE"),
    ("MED-PT-013", "RTPNOTICIAS", "RTP Notícias", "PT", "Portugal", "pt",
     "Télévision", "Audiovisuel", "Continu", "Généraliste",
     "Nationale", "RTP", "Lisbonne", "https://www.rtp.pt/noticias", 1, True,
     "Marque info RTP ; confiance DNR 2026 la plus élevée (79 %).", "CIBLE"),
    ("MED-PT-014", "SIC", "SIC", "PT", "Portugal", "pt",
     "Télévision", "Audiovisuel", "Continu", "Généraliste",
     "Nationale", "Impresa (MFE actionnaire 2026)", "Lisbonne", "https://sic.pt",
     1, True, "Chaîne privée leader d'audience 2026.", "CIBLE"),
    ("MED-PT-015", "SICN", "SIC Notícias", "PT", "Portugal", "pt",
     "Télévision", "Audiovisuel", "Continu", "Généraliste",
     "Nationale", "Impresa (MFE actionnaire 2026)", "Lisbonne", "https://sicnoticias.pt",
     1, True, "Chaîne d'info ; portée hebdo SIC+SICN ~60 % (DNR 2026).", "CIBLE"),
    ("MED-PT-016", "TVI", "TVI", "PT", "Portugal", "pt",
     "Télévision", "Audiovisuel", "Continu", "Généraliste",
     "Nationale", "Media Capital", "Queluz de Baixo", "https://tvi.iol.pt", 1, True,
     "Chaîne privée généraliste.", "CIBLE"),
    ("MED-PT-017", "CNNPT", "CNN Portugal", "PT", "Portugal", "pt",
     "Télévision", "Audiovisuel", "Continu", "Généraliste",
     "Nationale", "Media Capital", "Queluz de Baixo", "https://cnnportugal.iol.pt",
     1, True, "Chaîne d'info ; 2e portée hebdo DNR 2026 (~40 %).", "CIBLE"),
    ("MED-PT-018", "CMTV", "CMTV", "PT", "Portugal", "pt",
     "Télévision", "Audiovisuel", "Continu", "Généraliste",
     "Nationale", "Medialivre", "Lisbonne", "https://www.cm-tv.pt", 2, True,
     "Chaîne d'info populaire liée au Correio da Manhã.", "CIBLE"),
    ("MED-PT-019", "ANTENA1", "Antena 1", "PT", "Portugal", "pt",
     "Radio", "Audiovisuel", "Continu", "Généraliste",
     "Nationale", "RTP", "Lisbonne", "https://www.rtp.pt/antena1", 2, True,
     "Radio généraliste de service public.", "CIBLE"),
    ("MED-PT-020", "TSF", "TSF", "PT", "Portugal", "pt",
     "Radio", "Audiovisuel", "Continu", "Généraliste",
     "Nationale", "Global Media Group", "Lisbonne", "https://www.tsf.pt", 2, True,
     "Radio d'information de référence.", "CIBLE"),
    ("MED-PT-021", "RENASCENCA", "Rádio Renascença", "PT", "Portugal", "pt",
     "Radio", "Audiovisuel", "Continu", "Généraliste",
     "Nationale", "Renascença Multimédia", "Lisbonne", "https://rr.sapo.pt", 2, True,
     "Radio généraliste (groupe catholique).", "CIBLE"),
    ("MED-PT-022", "RFM", "RFM", "PT", "Portugal", "pt",
     "Radio", "Audiovisuel", "Continu", "Généraliste",
     "Nationale", "Renascença Multimédia", "Lisbonne", "https://rfm.sapo.pt", 3, True,
     "Radio musicale à forte audience.", "CIBLE"),
    ("MED-PT-023", "RADIOOBS", "Rádio Observador", "PT", "Portugal", "pt",
     "Radio", "Audiovisuel", "Continu", "Généraliste",
     "Nationale", "Observador On Time", "Lisbonne", "https://observador.pt/radio",
     2, True, "Radio du pure player Observador.", "CIBLE"),
    ("MED-PT-024", "LUSA", "Lusa", "PT", "Portugal", "pt",
     "Agence de presse", "Agence", "Continu", "Généraliste",
     "Nationale", "Lusa (État portugais)", "Lisbonne", "https://www.lusa.pt", 1, True,
     "Agence nationale ; propriété 100 % État. Fil prioritaire des CP.", "CIBLE"),
    ("MED-PT-025", "SAPO", "SAPO", "PT", "Portugal", "pt",
     "Web natif", "Digital", "Continu", "Généraliste",
     "Nationale", "Altice Portugal", "Lisbonne", "https://www.sapo.pt", 2, True,
     "Portail d'agrégation / audience digitale large.", "CIBLE"),
    ("MED-PT-026", "NAM", "Notícias ao Minuto", "PT", "Portugal", "pt",
     "Web natif", "Digital", "Continu", "Généraliste",
     "Nationale", "Notícias ao Minuto", "Lisbonne", "https://www.noticiasaominuto.com",
     2, True, "Pure player à forte portée digitale (DNR 2026 ~27 %).", "CIBLE"),
    ("MED-PT-027", "RECORD", "Record", "PT", "Portugal", "pt",
     "Presse quotidienne", "Print+Digital", "Quotidien", "Sport",
     "Nationale", "Medialivre", "Lisbonne", "https://www.record.pt", 3, True,
     "Quotidien sportif. Utile si angle sport / sponsoring.", "CIBLE"),
    ("MED-PT-028", "JE", "Jornal Económico", "PT", "Portugal", "pt",
     "Presse quotidienne", "Print+Digital", "Quotidien", "Économie",
     "Nationale", "Grupo Económico", "Lisbonne", "https://jornaleconomico.sapo.pt",
     2, True, "Quotidien / site économique.", "CIBLE"),
    # --- Espagne ---
    ("MED-ES-001", "ELPAIS", "El País", "ES", "Espagne", "es",
     "Presse quotidienne", "Print+Digital", "Quotidien", "Généraliste",
     "Nationale", "PRISA", "Madrid", "https://elpais.com", 1, True,
     "Leader presse généraliste EGM 2026 (856k lecteurs ; 7,7 M VU web).", "CIBLE"),
    ("MED-ES-002", "ELMUNDO", "El Mundo", "ES", "Espagne", "es",
     "Presse quotidienne", "Print+Digital", "Quotidien", "Généraliste",
     "Nationale", "Unidad Editorial", "Madrid", "https://www.elmundo.es", 1, True,
     "2e quotidien généraliste EGM 2026 (505k).", "CIBLE"),
    ("MED-ES-003", "ABC", "ABC", "ES", "Espagne", "es",
     "Presse quotidienne", "Print+Digital", "Quotidien", "Généraliste",
     "Nationale", "Vocento", "Madrid", "https://www.abc.es", 1, True,
     "Quotidien national conservateur (345k EGM 2026).", "CIBLE"),
    ("MED-ES-004", "LAVANGUARDIA", "La Vanguardia", "ES", "Espagne", "es",
     "Presse quotidienne", "Print+Digital", "Quotidien", "Généraliste",
     "Nationale", "Grupo Godó", "Barcelone", "https://www.lavanguardia.com", 1, True,
     "Quotidien barcelonais à portée nationale (386k EGM 2026). Aussi en catalan.", "CIBLE"),
    ("MED-ES-005", "ELPERIODICO", "El Periódico", "ES", "Espagne", "es",
     "Presse quotidienne", "Print+Digital", "Quotidien", "Généraliste",
     "Nationale", "Prensa Ibérica", "Barcelone", "https://www.elperiodico.com", 2, True,
     "Quotidien barcelonais (185k EGM 2026). Éditions ES/CA.", "CIBLE"),
    ("MED-ES-006", "LARAZON", "La Razón", "ES", "Espagne", "es",
     "Presse quotidienne", "Print+Digital", "Quotidien", "Généraliste",
     "Nationale", "Grupo Planeta", "Madrid", "https://www.larazon.es", 2, True,
     "Quotidien national (129k EGM 2026).", "CIBLE"),
    ("MED-ES-007", "20MIN", "20 Minutos", "ES", "Espagne", "es",
     "Presse quotidienne", "Print+Digital", "Quotidien", "Généraliste",
     "Nationale", "Henneo", "Madrid", "https://www.20minutos.es", 2, True,
     "Gratuit / digital grand public (238k EGM 2026).", "CIBLE"),
    ("MED-ES-008", "ELCONFIDENCIAL", "El Confidencial", "ES", "Espagne", "es",
     "Web natif", "Digital", "Continu", "Généraliste",
     "Nationale", "Titania Compañía Editorial", "Madrid", "https://www.elconfidencial.com",
     1, True, "Pure player national, fort éco / enquête.", "CIBLE"),
    ("MED-ES-009", "ELDIARIO", "elDiario.es", "ES", "Espagne", "es",
     "Web natif", "Digital", "Continu", "Généraliste",
     "Nationale", "Diario de Prensa Digital", "Madrid", "https://www.eldiario.es",
     1, True, "Pure player progressiste, modèle lecteurs.", "CIBLE"),
    ("MED-ES-010", "ARA", "Ara", "ES", "Espagne", "ca",
     "Presse quotidienne", "Print+Digital", "Quotidien", "Généraliste",
     "Régionale", "Edició de Premsa Periòdica Ara", "Barcelone", "https://www.ara.cat",
     2, True, "Quotidien catalan de référence.", "CIBLE"),
    ("MED-ES-011", "LAVOZ", "La Voz de Galicia", "ES", "Espagne", "es",
     "Presse quotidienne", "Print+Digital", "Quotidien", "Régional",
     "Régionale", "Corporación Voz de Galicia", "La Corogne", "https://www.lavozdegalicia.es",
     2, True, "PQR galicienne (296k EGM 2026).", "CIBLE"),
    ("MED-ES-012", "ELCORREO", "El Correo", "ES", "Espagne", "es",
     "Presse quotidienne", "Print+Digital", "Quotidien", "Régional",
     "Régionale", "Vocento", "Bilbao", "https://www.elcorreo.com", 2, True,
     "PQR basque (203k EGM 2026).", "CIBLE"),
    ("MED-ES-013", "EXPANSION", "Expansión", "ES", "Espagne", "es",
     "Presse quotidienne", "Print+Digital", "Quotidien", "Économie",
     "Nationale", "Unidad Editorial", "Madrid", "https://www.expansion.com", 1, True,
     "Quotidien économique de référence.", "CIBLE"),
    ("MED-ES-014", "CINCODIAS", "Cinco Días", "ES", "Espagne", "es",
     "Presse quotidienne", "Print+Digital", "Quotidien", "Économie",
     "Nationale", "PRISA", "Madrid", "https://cincodias.elpais.com", 1, True,
     "Quotidien économique du groupe El País.", "CIBLE"),
    ("MED-ES-015", "ELECONOMISTA", "El Economista", "ES", "Espagne", "es",
     "Presse quotidienne", "Print+Digital", "Quotidien", "Économie",
     "Nationale", "Editorial Ecoprensa", "Madrid", "https://www.eleconomista.es", 2, True,
     "Quotidien / site éco (1,4 M VU EGM 2026).", "CIBLE"),
    ("MED-ES-016", "MARCA", "Marca", "ES", "Espagne", "es",
     "Presse quotidienne", "Print+Digital", "Quotidien", "Sport",
     "Nationale", "Unidad Editorial", "Madrid", "https://www.marca.com", 2, True,
     "1er quotidien en lecteurs EGM 2026 (881k). Angle sport uniquement.", "CIBLE"),
    ("MED-ES-017", "AS", "AS", "ES", "Espagne", "es",
     "Presse quotidienne", "Print+Digital", "Quotidien", "Sport",
     "Nationale", "PRISA", "Madrid", "https://as.com", 2, True,
     "Quotidien sportif (369k EGM ; 2,8 M VU web).", "CIBLE"),
    ("MED-ES-018", "TVE1", "TVE La 1", "ES", "Espagne", "es",
     "Télévision", "Audiovisuel", "Continu", "Généraliste",
     "Nationale", "RTVE", "Madrid", "https://www.rtve.es/television/la-1", 1, True,
     "Chaîne public, 2e audience TV (13,6 % EGM/audimétrie 2026).", "CIBLE"),
    ("MED-ES-019", "ANTENA3", "Antena 3", "ES", "Espagne", "es",
     "Télévision", "Audiovisuel", "Continu", "Généraliste",
     "Nationale", "Atresmedia", "Madrid", "https://www.antena3.com", 1, True,
     "Leader TV 2026 (16,9 % de part d'audience).", "CIBLE"),
    ("MED-ES-020", "TELECINCO", "Telecinco", "ES", "Espagne", "es",
     "Télévision", "Audiovisuel", "Continu", "Généraliste",
     "Nationale", "Mediaset España / MFE", "Madrid", "https://www.telecinco.es", 1, True,
     "3e chaîne (9,4 % 2026).", "CIBLE"),
    ("MED-ES-021", "LASEXTA", "La Sexta", "ES", "Espagne", "es",
     "Télévision", "Audiovisuel", "Continu", "Généraliste",
     "Nationale", "Atresmedia", "Madrid", "https://www.lasexta.com", 1, True,
     "Chaîne info / débat, utile pour angles société / politique.", "CIBLE"),
    ("MED-ES-022", "TV3", "TV3", "ES", "Espagne", "ca",
     "Télévision", "Audiovisuel", "Continu", "Généraliste",
     "Régionale", "CCMA", "Sant Joan Despí", "https://www.ccma.cat/tv3", 2, True,
     "Chaîne publique catalane.", "CIBLE"),
    ("MED-ES-023", "SER", "Cadena SER", "ES", "Espagne", "es",
     "Radio", "Audiovisuel", "Continu", "Généraliste",
     "Nationale", "PRISA", "Madrid", "https://cadenaser.com", 1, True,
     "Leader radio généraliste (4,17 M auditeurs EGM 2026).", "CIBLE"),
    ("MED-ES-024", "COPE", "COPE", "ES", "Espagne", "es",
     "Radio", "Audiovisuel", "Continu", "Généraliste",
     "Nationale", "Ábside Media", "Madrid", "https://www.cope.es", 1, True,
     "2e radio généraliste (3,41 M EGM 2026).", "CIBLE"),
    ("MED-ES-025", "ONDACERO", "Onda Cero", "ES", "Espagne", "es",
     "Radio", "Audiovisuel", "Continu", "Généraliste",
     "Nationale", "Atresmedia", "Madrid", "https://www.ondacero.es", 2, True,
     "3e radio généraliste (2,09 M EGM 2026).", "CIBLE"),
    ("MED-ES-026", "RNE", "RNE", "ES", "Espagne", "es",
     "Radio", "Audiovisuel", "Continu", "Généraliste",
     "Nationale", "RTVE", "Madrid", "https://www.rtve.es/radio", 2, True,
     "Radio nationale de service public (920k EGM 2026).", "CIBLE"),
    ("MED-ES-027", "RAC1", "RAC1", "ES", "Espagne", "ca",
     "Radio", "Audiovisuel", "Continu", "Généraliste",
     "Régionale", "Grupo Godó", "Barcelone", "https://www.rac1.cat", 2, True,
     "Leader radio en Catalogne (960k EGM 2026).", "CIBLE"),
    ("MED-ES-028", "EFE", "EFE", "ES", "Espagne", "es",
     "Agence de presse", "Agence", "Continu", "Généraliste",
     "Internationale", "Agencia EFE", "Madrid", "https://www.efe.com", 1, True,
     "Agence nationale / hispanophone. Fil prioritaire des CP.", "CIBLE"),
    ("MED-ES-029", "EUROPAPRESS", "Europa Press", "ES", "Espagne", "es",
     "Agence de presse", "Agence", "Continu", "Généraliste",
     "Nationale", "Europa Press", "Madrid", "https://www.europapress.es", 1, True,
     "Agence privée, très utilisée par les rédactions.", "CIBLE"),
    ("MED-ES-030", "RTVEWEB", "RTVE.es", "ES", "Espagne", "es",
     "Web natif", "Digital", "Continu", "Généraliste",
     "Nationale", "RTVE", "Madrid", "https://www.rtve.es", 1, True,
     "3e site d'info EGM 2026 (4,5 M VU). Hub numérique du service public.", "CIBLE"),
    ("MED-ES-031", "ELESPANOL", "El Español", "ES", "Espagne", "es",
     "Web natif", "Digital", "Continu", "Généraliste",
     "Nationale", "El León de El Español Publicaciones", "Madrid", "https://www.elespanol.com",
     2, True, "Pure player national.", "CIBLE"),
    ("MED-ES-032", "OKDIARIO", "OKDiario", "ES", "Espagne", "es",
     "Web natif", "Digital", "Continu", "Généraliste",
     "Nationale", "Acción Digital", "Madrid", "https://okdiario.com", 3, True,
     "Pure player d'opinion ; ligne très polarisée.", "CIBLE"),
    ("MED-ES-033", "VILAWEB", "VilaWeb", "ES", "Espagne", "ca",
     "Web natif", "Digital", "Continu", "Généraliste",
     "Régionale", "Partal, Maresma i Associats", "Barcelone", "https://www.vilaweb.cat",
     3, True, "Pure player catalan.", "CIBLE"),
    ("MED-ES-034", "LNE", "La Nueva España", "ES", "Espagne", "es",
     "Presse quotidienne", "Print+Digital", "Quotidien", "Régional",
     "Régionale", "Prensa Ibérica", "Oviedo", "https://www.lne.es", 3, True,
     "PQR des Asturies (158k EGM 2026).", "CIBLE"),
    ("MED-ES-035", "DVASCO", "El Diario Vasco", "ES", "Espagne", "es",
     "Presse quotidienne", "Print+Digital", "Quotidien", "Régional",
     "Régionale", "Vocento", "Saint-Sébastien", "https://www.diariovasco.com", 3, True,
     "PQR du Guipuscoa (131k EGM 2026).", "CIBLE"),
]


def as_records() -> list[dict[str, object]]:
    records = []
    for row in ROWS:
        rec = dict(zip(COLUMNS, row))
        rec["actif"] = "true" if rec["actif"] else "false"
        rec["priorite_rp"] = int(rec["priorite_rp"])
        records.append(rec)
    return records


def sql_literal(value: object) -> str:
    if isinstance(value, bool):
        return "TRUE" if value else "FALSE"
    if isinstance(value, int):
        return str(value)
    text = str(value).replace("'", "''")
    return f"'{text}'"


def write_csv(path: Path, records: list[dict[str, object]]) -> None:
    with path.open("w", encoding="utf-8", newline="") as fh:
        writer = csv.DictWriter(fh, fieldnames=COLUMNS)
        writer.writeheader()
        writer.writerows(records)


def write_json(path: Path, records: list[dict[str, object]]) -> None:
    typed = []
    for rec in records:
        item = dict(rec)
        item["actif"] = rec["actif"] == "true"
        typed.append(item)
    path.write_text(json.dumps(typed, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def write_sql(path: Path) -> None:
    lines = [
        "-- Référentiel médias — table ref_media",
        "-- Généré pour import PostgreSQL / compatible MySQL (TINYINT pour actif si besoin).",
        "",
        "CREATE TABLE IF NOT EXISTS ref_media (",
        "    id_media      VARCHAR(16)  PRIMARY KEY,",
        "    code          VARCHAR(32)  NOT NULL UNIQUE,",
        "    nom           VARCHAR(120) NOT NULL,",
        "    pays_code     CHAR(2)      NOT NULL,",
        "    pays_nom      VARCHAR(40)  NOT NULL,",
        "    langue        VARCHAR(8)   NOT NULL,",
        "    type_media    VARCHAR(40)  NOT NULL,",
        "    support       VARCHAR(24)  NOT NULL,",
        "    periodicite   VARCHAR(24)  NOT NULL,",
        "    thematique    VARCHAR(32)  NOT NULL,",
        "    couverture    VARCHAR(24)  NOT NULL,",
        "    groupe_media  VARCHAR(80)  NOT NULL,",
        "    ville         VARCHAR(60)  NOT NULL,",
        "    url           VARCHAR(255) NOT NULL,",
        "    priorite_rp   SMALLINT     NOT NULL,",
        "    actif         BOOLEAN      NOT NULL DEFAULT TRUE,",
        "    notes         TEXT,",
        "    source_liste  VARCHAR(16)  NOT NULL",
        ");",
        "",
        "CREATE INDEX IF NOT EXISTS idx_ref_media_pays ON ref_media (pays_code);",
        "CREATE INDEX IF NOT EXISTS idx_ref_media_type ON ref_media (type_media);",
        "CREATE INDEX IF NOT EXISTS idx_ref_media_prio ON ref_media (priorite_rp);",
        "",
        "DELETE FROM ref_media WHERE pays_code IN ('FR', 'BE', 'CH', 'PT', 'ES');",
        "",
        "INSERT INTO ref_media (",
        "    id_media, code, nom, pays_code, pays_nom, langue, type_media, support,",
        "    periodicite, thematique, couverture, groupe_media, ville, url,",
        "    priorite_rp, actif, notes, source_liste",
        ") VALUES",
    ]
    value_rows = []
    for raw in ROWS:
        rec = dict(zip(COLUMNS, raw))
        values = ", ".join(sql_literal(rec[col] if col != "actif" else bool(raw[15])) for col in COLUMNS)
        value_rows.append(f"    ({values})")
    lines.append(",\n".join(value_rows) + ";")
    lines.append("")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def md_escape(text: object) -> str:
    return str(text).replace("|", "\\|")


def write_catalog(path: Path, records: list[dict[str, object]]) -> None:
    by_country: dict[str, list[dict[str, object]]] = {}
    for rec in records:
        by_country.setdefault(str(rec["pays_nom"]), []).append(rec)

    order = ["France", "Belgique", "Suisse", "Portugal", "Espagne"]
    lines = [
        "# Catalogue médias — `ref_media`",
        "",
        "Liste opérationnelle pour relations presse. Les lignes **France** (`source_liste = EXEMPLE`) calent le format de la table. Les pays demandés sont en `source_liste = CIBLE`.",
        "",
        "Priorité RP : **1** incontournable · **2** important · **3** complémentaire.",
        "",
    ]
    for country in order:
        rows = by_country.get(country, [])
        if not rows:
            continue
        tag = "exemple de structure" if country == "France" else "liste cible"
        lines.append(f"## {country} ({len(rows)} médias — {tag})")
        lines.append("")
        lines.append("| id | Nom | Type | Thématique | Langue | Groupe | Priorité | URL |")
        lines.append("|---|---|---|---|---|---|---|---|")
        for rec in rows:
            lines.append(
                "| {id} | {nom} | {typ} | {thm} | {lang} | {grp} | {prio} | {url} |".format(
                    id=rec["id_media"],
                    nom=md_escape(rec["nom"]),
                    typ=md_escape(rec["type_media"]),
                    thm=md_escape(rec["thematique"]),
                    lang=rec["langue"],
                    grp=md_escape(rec["groupe_media"]),
                    prio=rec["priorite_rp"],
                    url=rec["url"],
                )
            )
        lines.append("")
    path.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    here = Path(__file__).resolve().parent
    records = as_records()
    write_csv(here / "ref_media.csv", records)
    write_json(here / "ref_media.json", records)
    write_sql(here / "ref_media.sql")
    write_catalog(here / "CATALOGUE.md", records)
    counts: dict[str, int] = {}
    for rec in records:
        counts[str(rec["pays_code"])] = counts.get(str(rec["pays_code"]), 0) + 1
    print("écrit", len(records), "lignes", counts)


if __name__ == "__main__":
    main()
